#!/bin/bash

red='\033[0;31m'
nc='\033[0m'
path=$1
pipe=false

function ACK_IT
{
  if $pipe
  then
    ack --nocolor "$1" $path
  else
    ack -iHR "$1" $path
  fi
}

function PRETTY_PRINT
{
  if $pipe
  then
    echo $1
  else
    echo -e "${red}$1${nc}"
  fi
}

PRETTY_PRINT '------------'
PRETTY_PRINT 'Drupack v0.2'
PRETTY_PRINT '------------'
echo

PRETTY_PRINT 'Using node title:'
ACK_IT "\\\$node->title"
echo

PRETTY_PRINT 'Menu access callback:'
ACK_IT 'access callback'
echo

PRETTY_PRINT 'Menu access arguments:'
ACK_IT 'access arguments'
echo

PRETTY_PRINT 'Not using l or url:'
ACK_IT "<a\\b.*\\\$"
echo

PRETTY_PRINT 'Directly accessing value:'
ACK_IT "\]\['value'\]"
echo

PRETTY_PRINT 'SQL Injection:'
ACK_IT "((db_query|db_select)(\\(['\"].*\\\$.*))|(\\b(SELECT|LIKE|CONCAT|AND|ON|LEFT|WHERE)\\b.*['\"].*\\\$.*['\"])" $1
echo

PRETTY_PRINT 'Super Global Input:'
ACK_IT "(\\\$_GET|\\\$_POST|\\\$_REQUEST)"
echo

PRETTY_PRINT 'arg() usage:'
ACK_IT " arg\\("
echo

PRETTY_PRINT '$user use:'
ACK_IT "\\\$user\\b"
echo

PRETTY_PRINT 'Using drupal_set_message:'
ACK_IT 'drupal_set_message\('
echo

PRETTY_PRINT 'Use of Echo/Print:'
ACK_IT "(\\becho\\b|\\bprint\\b)"
echo

PRETTY_PRINT 'Use of debug functions:'
ACK_IT "(\\bvar_dump\\b|\\bvar_export\\b|\\bprint_r\\b|\\bdsm\\b|\\bdpm\\b)"
echo

PRETTY_PRINT 'CrytoPHP:'
ACK_IT "(include|require).*?\(.*(jpg|png|gif|jpeg|txt)"
echo

PRETTY_PRINT ' '
exit 0
